/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lrkj_business_LrNativeApi */

#ifndef _Included_com_lrkj_business_LrNativeApi
#define _Included_com_lrkj_business_LrNativeApi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lrkj_business_LrNativeApi
 * Method:    setRobotIp
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_lrkj_business_LrNativeApi_setRobotIp
  (JNIEnv *, jclass, jstring);


JNIEXPORT jboolean JNICALL Java_com_lrkj_business_LrNativeApi_writeBitmapToPgm
        (JNIEnv *env, jclass, jstring path, jintArray buf, int w, int h);

/*
 * Class:     com_lrkj_business_LrNativeApi
 * Method:    getDotFrame
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_lrkj_utils_LrSocketSurfaceView_getDotFrame
        (JNIEnv *env, jclass clazz, jobject obj, jlong ioMat);

JNIEXPORT void JNICALL Java_com_lrkj_utils_LrSocketSurfaceView_stopDotSocket
        (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_lrkj_utils_LrSocketSurfaceView_saveLaserFrame
        (JNIEnv *env, jclass clazz);

JNIEXPORT jboolean JNICALL Java_com_lrkj_utils_LrSocketSurfaceView_getLaserFrame
    (JNIEnv *, jclass, jobject, jlong, jstring mappgm);
    
JNIEXPORT void JNICALL Java_com_lrkj_utils_LrSocketSurfaceView_stopLaserSocket
    (JNIEnv *, jclass);



// Navi

JNIEXPORT void JNICALL Java_com_lrkj_utils_LrSocketSurfaceView_getNaviFrame
        (JNIEnv *env, jclass clazz, jobject obj, jstring ipS, jstring map, jlong matMap, jlong ioMat, jint width, jint height);
JNIEXPORT void JNICALL Java_com_lrkj_utils_LrSocketSurfaceView_clickNaviTo
        (JNIEnv *env, jclass clazz, jint px, jint py, jfloat angle);

JNIEXPORT void JNICALL Java_com_lrkj_utils_LrSocketSurfaceView_stopNaviSocket
        (JNIEnv *, jclass);

// Map
JNIEXPORT jint JNICALL Java_com_lrkj_business_LrNativeApi_getAllMaps
        (JNIEnv *, jclass, jint);

JNIEXPORT jint JNICALL Java_com_lrkj_business_LrNativeApi_sendEditMap
        (JNIEnv *env, jclass clazz, jstring name, jstring mapPath);

#ifdef __cplusplus
}
#endif
#endif
