/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lrkj_business_LrNativeApi */

#ifndef _Included_com_lrkj_business_LrNativeApi
#define _Included_com_lrkj_business_LrNativeApi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lrkj_business_LrNativeApi
 * Method:    setRobotIp
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_lrkj_business_LrNativeApi_setRobotIp
  (JNIEnv *, jclass, jstring);


/*
 * Class:     com_lrkj_business_LrNativeApi
 * Method:    getDotFrame
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_lrkj_utils_LrSocketSurfaceView_getDotFrame
        (JNIEnv *, jclass, jobject, jlong);

JNIEXPORT void JNICALL Java_com_lrkj_utils_LrSocketSurfaceView_stopDotSocket
        (JNIEnv *, jclass);
    
    JNIEXPORT jboolean JNICALL Java_com_lrkj_utils_LrSocketSurfaceView_getLaserFrame
    (JNIEnv *, jclass, jobject, jlong);
    
    JNIEXPORT void JNICALL Java_com_lrkj_utils_LrSocketSurfaceView_stopLaserSocket
    (JNIEnv *, jclass);
    
    JNIEXPORT jint JNICALL Java_com_lrkj_business_LrNativeApi_getAllMaps
    (JNIEnv *, jclass);


// Navi

JNIEXPORT void JNICALL Java_com_lrkj_utils_LrSocketSurfaceView_getNaviFrame
        (JNIEnv *env, jclass clazz, jobject obj, jstring ipS, jlong ioMat);
JNIEXPORT void JNICALL Java_com_lrkj_utils_LrSocketSurfaceView_clickNaviTo
        (JNIEnv *env, jclass clazz, jint px, jint py);

JNIEXPORT void JNICALL Java_com_lrkj_utils_LrSocketSurfaceView_stopNaviSocket
        (JNIEnv *, jclass);


#ifdef __cplusplus
}
#endif
#endif
