/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hwj_opencvjni_OpenCVHelper */

#ifndef _Included_hwj_opencvjni_OpenCVHelper
#define _Included_hwj_opencvjni_OpenCVHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hwj_opencvjni_OpenCVHelper
 * Method:    getStringTmp
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hwj_opencvjni_OpenCVHelper_getStringTmp
  (JNIEnv *, jclass);

JNIEXPORT jintArray JNICALL Java_hwj_opencvjni_OpenCVHelper_getGrayImage
  (JNIEnv *env, jobject, jintArray buf, int w, int h);

#ifdef __cplusplus
}
#endif
#endif
